### ISSUE TITLE
Grouping of CADF actions

### ISSUE THREAD

**Issue by auhlig** [sapcc/openstack-rate-limit-middleware#8]
Use case: A single rate limit for read/write requests.

Instead of defining a rate limit for multiple write actions and accounting request separately
```yaml
rates:
  default:
    account/container/object:
      - action: update
        limit: 100r/m

      - action: delete
        limit: 100r/m
```
one should be able to define a group of CADF actions
```yaml
groups:
  write:
    - update
    - delete
```
and the corresponding rate limit
```yaml
rates:
  default:
    account/container/object:
      - action: write
        limit: 100r/m
```
to account delete and update requests to an object as one rate.
